[package]
name = "editor-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tad-core = { path = "../tad-core" }
canvas-engine = { path = "../canvas-engine" }
serde.workspace = true
cgmath.workspace = true
anyhow.workspace = true
tracing.workspace = true
ahash.workspace = true
parking_lot.workspace = true
